export function safeStorageGet(key, fallback = null) {
  try { return window.localStorage?.getItem(key) ?? fallback; } catch { return fallback; }
}
export function safeStorageSet(key, value) {
  try { window.localStorage?.setItem(key, value); } catch {}
}
export function safeStorageRemove(key) {
  try { window.localStorage?.removeItem(key); } catch {}
}


export const LANGUAGE_PACKS = {
  zh: { name:'中文', back:'← 返回星图', bridge:'舰桥模式', daylight:'日间模式', themeAria:'切换主题', langAria:'切换语言', overviewTitle:'资产总览', overviewKicker:'FLEET ASSET OVERVIEW', dataUpdated:'数据更新时间', totalNodes:'总节点', online:'在线', warn:'波动', offline:'离线', expiresToday:'今日到期', within3Days:'3 日内', within7Days:'7 日内', monthlyTotalCost:'月付总成本', yearlyTotalCost:'年付总成本', expiringNodes:'到期节点', abnormalNodes:'异常节点', monthlyByRegion:'按地区月均', monthlyByProvider:'按供应商月均', noExpiring:'暂无临近到期', noAbnormal:'暂无异常节点', noData:'暂无数据', noAssets:'暂无资产', unknownNode:'未命名节点', unknownProvider:'未知供应商', unknownRegion:'未知地区', residualValue:'剩余价值', networkDetails:'NETWORK DETAILS', nodeNetworkDetails:'节点网络详情表', tableNodeId:'节点ID', geoLocation:'地理位置', operator:'运营商', monthlyTraffic:'月流量', packetLoss:'包丢失率', noNetworkData:'暂无节点网络数据', nodeTelemetry:'节点遥测', allocation:'分配', resources:'资源', bandwidth:'带宽', errorLog:'错误日志', fatalCodes:'故障码', nodeId:'节点 ID:', sector:'区段', systemCore:'系统核心', runtime:'运行时间', expiry:'到期', onlineSecure:'量子安全', ip:'IP', arch:'架构', memory:'内存', disk:'磁盘', geoCoords:'地理坐标', uuid:'UUID', swap:'交换', cpu:'CPU', mem:'内存', load:'负载', cores:'核心', uplink:'上行', downlink:'下行', traffic:'流量', liveTransfer:'实时传输', totalTraffic:'累计流量', fleetDb:'舰队资产数据库', identity:'身份', supplier:'供应商', city:'城市', multiNode:'多节点探针', probeLatency:'探针延迟', probe:'探针', loss:'丢包', telegramRules:'Telegram 规则', assetIndex:'资产向量索引', asset:'资产', node:'节点', vector:'向量', state:'状态', dataFreshness:'数据新鲜度', latestSample:'最新采样', sampleInterval:'采样间隔' },
  en: { name:'English', back:'← Starmap', bridge:'Bridge Mode', daylight:'Day Mode', themeAria:'Switch theme', langAria:'Switch language', overviewTitle:'Asset Overview', overviewKicker:'FLEET ASSET OVERVIEW', dataUpdated:'Updated', totalNodes:'Total Nodes', online:'Online', warn:'Degraded', offline:'Offline', expiresToday:'Due Today', within3Days:'Within 3 Days', within7Days:'Within 7 Days', monthlyTotalCost:'Monthly Total Cost', yearlyTotalCost:'Yearly Total Cost', expiringNodes:'Expiring Nodes', abnormalNodes:'Abnormal Nodes', monthlyByRegion:'Monthly by Region', monthlyByProvider:'Monthly by Provider', noExpiring:'No upcoming expiry', noAbnormal:'No abnormal nodes', noData:'No data', noAssets:'No assets', unknownNode:'Unnamed Node', unknownProvider:'Unknown Provider', unknownRegion:'Unknown Region', residualValue:'Residual Value', networkDetails:'NETWORK DETAILS', nodeNetworkDetails:'Node Network Details', tableNodeId:'Node ID', geoLocation:'Location', operator:'Operator', monthlyTraffic:'Monthly Traffic', packetLoss:'Packet Loss', noNetworkData:'No network data', nodeTelemetry:'Node Telemetry', allocation:'Allocation', resources:'Resources', bandwidth:'Bandwidth', errorLog:'Error Log', fatalCodes:'Fatal codes', nodeId:'Node ID:', sector:'Sector', systemCore:'System Core', runtime:'Runtime', expiry:'Expiry', onlineSecure:'Quantum Secure', ip:'IP', arch:'Arch', memory:'Memory', disk:'Disk', geoCoords:'Geo-Coords', uuid:'UUID', swap:'Swap', cpu:'CPU', mem:'Mem', load:'Load', cores:'cores', uplink:'Uplink', downlink:'Downlink', traffic:'Traffic', liveTransfer:'Live Transfer', totalTraffic:'Total Traffic', fleetDb:'Fleet Asset Database', identity:'Identity', supplier:'Supplier', city:'City', multiNode:'Multi-Node Probes', probeLatency:'Probe Latency', probe:'Probe', loss:'loss', telegramRules:'Telegram Rules', assetIndex:'Asset Vector Index', asset:'Asset', node:'Node', vector:'Vector', state:'State', dataFreshness:'Data Freshness', latestSample:'Latest Sample', sampleInterval:'Sample Interval' },
  ja: { name:'日本語', back:'← 星図へ', bridge:'艦橋', daylight:'昼間', themeAria:'テーマ切替', langAria:'言語切替', nodeTelemetry:'ノード遠隔測定', allocation:'割当', resources:'リソース', bandwidth:'帯域幅', errorLog:'エラーログ', fatalCodes:'致命コード', nodeId:'ノード ID:', sector:'セクター', systemCore:'システム中枢', runtime:'稼働時間', expiry:'期限', onlineSecure:'量子安全', ip:'IP', arch:'構成', memory:'メモリ', disk:'ディスク', geoCoords:'座標', uuid:'UUID', swap:'スワップ', cpu:'CPU', mem:'メモリ', load:'負荷', cores:'コア', uplink:'上り', downlink:'下り', traffic:'通信量', liveTransfer:'リアルタイム転送', totalTraffic:'累計通信量', fleetDb:'艦隊資産DB', identity:'識別', supplier:'供給元', city:'都市', multiNode:'多ノード探査', probeLatency:'探査遅延', probe:'探査', loss:'損失', telegramRules:'Telegram 规则', assetIndex:'資産ベクトル', asset:'資産', node:'ノード', vector:'ベクトル', state:'状態' },
  ko: { name:'한국어', back:'← 성도', bridge:'함교', daylight:'주간', themeAria:'테마 전환', langAria:'언어 전환', nodeTelemetry:'노드 텔레메트리', allocation:'할당', resources:'리소스', bandwidth:'대역폭', errorLog:'오류 로그', fatalCodes:'치명 코드', nodeId:'노드 ID:', sector:'섹터', systemCore:'시스템 코어', runtime:'가동 시간', expiry:'만료', onlineSecure:'양자 보안', ip:'IP', arch:'아키텍처', memory:'메모리', disk:'디스크', geoCoords:'좌표', uuid:'UUID', swap:'스왑', cpu:'CPU', mem:'메모리', load:'부하', cores:'코어', uplink:'업링크', downlink:'다운링크', traffic:'트래픽', liveTransfer:'실시간 전송', totalTraffic:'누적 트래픽', fleetDb:'함대 자산 DB', identity:'ID', supplier:'공급자', city:'도시', multiNode:'다중 노드 프로브', probeLatency:'프로브 지연', probe:'프로브', loss:'손실', telegramRules:'Telegram 규칙', assetIndex:'자산 벡터', asset:'자산', node:'노드', vector:'벡터', state:'상태' },
  es: { name:'Español', back:'← Mapa estelar', bridge:'Puente', daylight:'Día', themeAria:'Cambiar tema', langAria:'Cambiar idioma', nodeTelemetry:'Telemetría', allocation:'Asignación', resources:'Recursos', bandwidth:'Ancho de banda', errorLog:'Registro de errores', fatalCodes:'Códigos fatales', nodeId:'ID de nodo:', sector:'Sector', systemCore:'Núcleo', runtime:'Tiempo activo', expiry:'Vencimiento', onlineSecure:'Seguro cuántico', ip:'IP', arch:'Arquitectura', memory:'Memoria', disk:'Disco', geoCoords:'Coordenadas', uuid:'UUID', swap:'Swap', cpu:'CPU', mem:'Mem', load:'Carga', cores:'núcleos', uplink:'Subida', downlink:'Bajada', traffic:'Tráfico', liveTransfer:'Transferencia en vivo', totalTraffic:'Tráfico total', fleetDb:'Base de activos', identity:'Identidad', supplier:'Proveedor', city:'Ciudad', multiNode:'Sondas multi-nodo', probeLatency:'Latencia', probe:'Sonda', loss:'pérdida', telegramRules:'Reglas Telegram', assetIndex:'Índice vectorial', asset:'Activo', node:'Nodo', vector:'Vector', state:'Estado' },
  fr: { name:'Français', back:'← Carte stellaire', bridge:'Passerelle', daylight:'Jour', themeAria:'Changer le thème', langAria:'Changer de langue', nodeTelemetry:'Télémétrie', allocation:'Allocation', resources:'Ressources', bandwidth:'Bande passante', errorLog:'Journal erreurs', fatalCodes:'Codes fatals', nodeId:'ID nœud :', sector:'Secteur', systemCore:'Cœur système', runtime:'Durée', expiry:'Expiration', onlineSecure:'Sécurité quantique', ip:'IP', arch:'Arch', memory:'Mémoire', disk:'Disque', geoCoords:'Coordonnées', uuid:'UUID', swap:'Swap', cpu:'CPU', mem:'Mémoire', load:'Charge', cores:'cœurs', uplink:'Montant', downlink:'Descendant', traffic:'Trafic', liveTransfer:'Transfert direct', totalTraffic:'Trafic total', fleetDb:'Base des actifs', identity:'Identité', supplier:'Fournisseur', city:'Ville', multiNode:'Sondes multi-nœuds', probeLatency:'Latence', probe:'Sonde', loss:'perte', telegramRules:'Règles Telegram', assetIndex:'Index vectoriel', asset:'Actif', node:'Nœud', vector:'Vecteur', state:'État' },
  de: { name:'Deutsch', back:'← Sternkarte', bridge:'Brücke', daylight:'Tageslicht', themeAria:'Theme wechseln', langAria:'Sprache wechseln', nodeTelemetry:'Node-Telemetrie', allocation:'Zuweisung', resources:'Ressourcen', bandwidth:'Bandbreite', errorLog:'Fehlerprotokoll', fatalCodes:'Fatale Codes', nodeId:'Knoten-ID:', sector:'Sektor', systemCore:'Systemkern', runtime:'Laufzeit', expiry:'Ablauf', onlineSecure:'Quantensicher', ip:'IP', arch:'Arch', memory:'Speicher', disk:'Datenträger', geoCoords:'Koordinaten', uuid:'UUID', swap:'Swap', cpu:'CPU', mem:'Speicher', load:'Last', cores:'Kerne', uplink:'Upload', downlink:'Download', traffic:'Traffic', liveTransfer:'Live-Transfer', totalTraffic:'Gesamttraffic', fleetDb:'Flotten-DB', identity:'Identität', supplier:'Anbieter', city:'Stadt', multiNode:'Multi-Node-Probes', probeLatency:'Probe-Latenz', probe:'Probe', loss:'Verlust', telegramRules:'Telegram-Regeln', assetIndex:'Asset-Vektorindex', asset:'Asset', node:'Node', vector:'Vektor', state:'Status' },
  ru: { name:'Русский', back:'← Звёздная карта', bridge:'Мостик', daylight:'День', themeAria:'Сменить тему', langAria:'Сменить язык', nodeTelemetry:'Телеметрия', allocation:'Распределение', resources:'Ресурсы', bandwidth:'Канал', errorLog:'Журнал ошибок', fatalCodes:'Критические коды', nodeId:'ID узла:', sector:'Сектор', systemCore:'Ядро системы', runtime:'Время работы', expiry:'Срок', onlineSecure:'Квантовая защита', ip:'IP', arch:'Арх', memory:'Память', disk:'Диск', geoCoords:'Координаты', uuid:'UUID', swap:'Swap', cpu:'CPU', mem:'Память', load:'Нагрузка', cores:'ядра', uplink:'Исходящий', downlink:'Входящий', traffic:'Трафик', liveTransfer:'Живая передача', totalTraffic:'Всего трафика', fleetDb:'База активов', identity:'Идентификатор', supplier:'Поставщик', city:'Город', multiNode:'Мульти-пробы', probeLatency:'Задержка', probe:'Проба', loss:'потери', telegramRules:'Правила Telegram', assetIndex:'Векторный индекс', asset:'Актив', node:'Узел', vector:'Вектор', state:'Состояние' },
};
// Dynamic detail/globe labels are created after the static DOM translation pass,
// so keep their localized vocabulary alongside the language packs.
Object.assign(LANGUAGE_PACKS.zh, { healthStatus:'健康状态', abnormal:'异常', attention:'需关注', healthy:'健康', agentOnline:'Agent 在线', agentOffline:'Agent 离线', critical:'严重', reminder:'提醒', alerts:'告警', latestSample:'最新采样', backendSampleInterval:'后端采样间隔', noSample:'无采样', secondsAgo:'秒前', minutesAgo:'分钟前', visitorBeacon:'访客信标' });
Object.assign(LANGUAGE_PACKS.en, { healthStatus:'Health status', abnormal:'Abnormal', attention:'Needs attention', healthy:'Healthy', agentOnline:'Agent online', agentOffline:'Agent offline', critical:'critical', reminder:'reminders', alerts:'alerts', latestSample:'Latest sample', backendSampleInterval:'Backend sample interval', noSample:'No sample', secondsAgo:'seconds ago', minutesAgo:'minutes ago', visitorBeacon:'Visitor beacon' });
Object.assign(LANGUAGE_PACKS.ja, { healthStatus:'健全性', abnormal:'異常', attention:'要確認', healthy:'正常', agentOnline:'エージェント接続中', agentOffline:'エージェント切断', critical:'重大', reminder:'注意', alerts:'アラート', latestSample:'最新サンプル', backendSampleInterval:'バックエンド間隔', noSample:'サンプルなし', secondsAgo:'秒前', minutesAgo:'分前', visitorBeacon:'訪問者ビーコン' });
Object.assign(LANGUAGE_PACKS.ko, { healthStatus:'상태', abnormal:'비정상', attention:'주의 필요', healthy:'정상', agentOnline:'에이전트 온라인', agentOffline:'에이전트 오프라인', critical:'심각', reminder:'알림', alerts:'경고', latestSample:'최근 샘플', backendSampleInterval:'백엔드 샘플 간격', noSample:'샘플 없음', secondsAgo:'초 전', minutesAgo:'분 전', visitorBeacon:'방문자 비콘' });
Object.assign(LANGUAGE_PACKS.es, { healthStatus:'Estado', abnormal:'Anómalo', attention:'Requiere atención', healthy:'Saludable', agentOnline:'Agente en línea', agentOffline:'Agente fuera de línea', critical:'crítico', reminder:'avisos', alerts:'alertas', latestSample:'Última muestra', backendSampleInterval:'Intervalo del backend', noSample:'Sin muestras', secondsAgo:'segundos atrás', minutesAgo:'minutos atrás', visitorBeacon:'Baliza de visitante' });
Object.assign(LANGUAGE_PACKS.fr, { healthStatus:'État', abnormal:'Anormal', attention:'À surveiller', healthy:'Sain', agentOnline:'Agent en ligne', agentOffline:'Agent hors ligne', critical:'critique', reminder:'alertes', alerts:'alertes', latestSample:'Dernier échantillon', backendSampleInterval:'Intervalle backend', noSample:'Aucun échantillon', secondsAgo:'secondes', minutesAgo:'minutes', visitorBeacon:'Balise visiteur' });
Object.assign(LANGUAGE_PACKS.de, { healthStatus:'Status', abnormal:'Anomal', attention:'Achtung', healthy:'Gesund', agentOnline:'Agent online', agentOffline:'Agent offline', critical:'kritisch', reminder:'Hinweise', alerts:'Warnungen', latestSample:'Letzte Messung', backendSampleInterval:'Backend-Intervall', noSample:'Keine Messung', secondsAgo:'Sekunden', minutesAgo:'Minuten', visitorBeacon:'Besucher-Bake' });
Object.assign(LANGUAGE_PACKS.ru, { healthStatus:'Состояние', abnormal:'Аномалия', attention:'Требует внимания', healthy:'Норма', agentOnline:'Агент онлайн', agentOffline:'Агент офлайн', critical:'критично', reminder:'предупреждения', alerts:'оповещения', latestSample:'Последняя выборка', backendSampleInterval:'Интервал сервера', noSample:'Нет выборок', secondsAgo:'секунд назад', minutesAgo:'минут назад', visitorBeacon:'Метка посетителя' });
// Detail chart-card titles are re-localized in place on language switch.
Object.assign(LANGUAGE_PACKS.zh, { chartNetworkThroughput:'网络吞吐量', chartPingLatency:'PING 延迟', chartCpuUsage:'CPU 使用率', chartMemoryUsage:'内存使用率', chartProcessCount:'运行进程数', chartDropLeavesGap:'掉线留空', chartRealtimeSampling:'实时采样', chartTargets:'目标', chartHours6:'6小时', chartHours1:'1小时', globalVpsProbeLatency:'全球 VPS 探针延迟', probeLinkState:'探针链路状态' });
Object.assign(LANGUAGE_PACKS.en, { chartNetworkThroughput:'Network throughput', chartPingLatency:'PING latency', chartCpuUsage:'CPU usage', chartMemoryUsage:'Memory usage', chartProcessCount:'Processes', chartDropLeavesGap:'gaps on drop', chartRealtimeSampling:'realtime', chartTargets:'targets', chartHours6:'6h', chartHours1:'1h', globalVpsProbeLatency:'Global VPS probe latency', probeLinkState:'Probe link state' });
Object.assign(LANGUAGE_PACKS.ja, { chartNetworkThroughput:'ネットワーク帯域', chartPingLatency:'PING 遅延', chartCpuUsage:'CPU 使用率', chartMemoryUsage:'メモリ使用率', chartProcessCount:'プロセス数', chartDropLeavesGap:'切断は空白', chartRealtimeSampling:'リアルタイム', chartTargets:'ターゲット', chartHours6:'6時間', chartHours1:'1時間', globalVpsProbeLatency:'グローバル VPS プローブ遅延', probeLinkState:'プローブ状態' });
Object.assign(LANGUAGE_PACKS.ko, { chartNetworkThroughput:'네트워크 처리량', chartPingLatency:'PING 지연', chartCpuUsage:'CPU 사용률', chartMemoryUsage:'메모리 사용률', chartProcessCount:'프로세스 수', chartDropLeavesGap:'끊김은 공백', chartRealtimeSampling:'실시간', chartTargets:'대상', chartHours6:'6시간', chartHours1:'1시간', globalVpsProbeLatency:'글로벌 VPS 프로브 지연', probeLinkState:'프로브 상태' });
Object.assign(LANGUAGE_PACKS.es, { chartNetworkThroughput:'Rendimiento de red', chartPingLatency:'Latencia PING', chartCpuUsage:'Uso de CPU', chartMemoryUsage:'Uso de memoria', chartProcessCount:'Procesos', chartDropLeavesGap:'huecos al caer', chartRealtimeSampling:'en tiempo real', chartTargets:'objetivos', chartHours6:'6 h', chartHours1:'1 h', globalVpsProbeLatency:'Latencia de sonda VPS global', probeLinkState:'Estado de sonda' });
Object.assign(LANGUAGE_PACKS.fr, { chartNetworkThroughput:'Débit réseau', chartPingLatency:'Latence PING', chartCpuUsage:'Utilisation CPU', chartMemoryUsage:'Utilisation mémoire', chartProcessCount:'Processus', chartDropLeavesGap:'vides si coupé', chartRealtimeSampling:'temps réel', chartTargets:'cibles', chartHours6:'6 h', chartHours1:'1 h', globalVpsProbeLatency:'Latence sonde VPS globale', probeLinkState:'État de la sonde' });
Object.assign(LANGUAGE_PACKS.de, { chartNetworkThroughput:'Netzwerkdurchsatz', chartPingLatency:'PING-Latenz', chartCpuUsage:'CPU-Auslastung', chartMemoryUsage:'Speicherauslastung', chartProcessCount:'Prozesse', chartDropLeavesGap:'Lücke bei Ausfall', chartRealtimeSampling:'Echtzeit', chartTargets:'Ziele', chartHours6:'6 Std', chartHours1:'1 Std', globalVpsProbeLatency:'Globale VPS-Sonden-Latenz', probeLinkState:'Sondenstatus' });
Object.assign(LANGUAGE_PACKS.ru, { chartNetworkThroughput:'Пропускная способность', chartPingLatency:'Задержка PING', chartCpuUsage:'Загрузка CPU', chartMemoryUsage:'Использование памяти', chartProcessCount:'Процессы', chartDropLeavesGap:'разрывы — пропуск', chartRealtimeSampling:'в реальном времени', chartTargets:'цели', chartHours6:'6 ч', chartHours1:'1 ч', globalVpsProbeLatency:'Глобальная задержка зонда VPS', probeLinkState:'Состояние зонда' });
// The detail health-summary row and the realtime panel headers are rewritten by the
// 5s live poll AFTER applyLanguage() has run, so every string the poll writes needs a
// key here — a literal there silently reverts the UI to Chinese one tick after the
// user switches language.
Object.assign(LANGUAGE_PACKS.zh, { healthResources:'资源', healthLink:'链路', healthPacketLoss:'丢包', probeTargetsCount:'个探测目标', noPeerProbeSamples:'暂无真实节点侧互探采样', waitingAgentReport:'等待 agent 上报', waitingAgent:'等待 agent', hostLevelMonitoring:'主机级监控', processUnit:'个' });
Object.assign(LANGUAGE_PACKS.en, { healthResources:'Resources', healthLink:'Link', healthPacketLoss:'Loss', probeTargetsCount:'probe targets', noPeerProbeSamples:'No peer probe samples yet', waitingAgentReport:'Waiting for agent report', waitingAgent:'Waiting for agent', hostLevelMonitoring:'Host-level monitoring', processUnit:'' });
Object.assign(LANGUAGE_PACKS.ja, { healthResources:'リソース', healthLink:'リンク', healthPacketLoss:'パケット損失', probeTargetsCount:'個の探査対象', noPeerProbeSamples:'ノード間探査のサンプルなし', waitingAgentReport:'エージェントの報告待ち', waitingAgent:'エージェント待ち', hostLevelMonitoring:'ホストレベル監視', processUnit:'個' });
Object.assign(LANGUAGE_PACKS.ko, { healthResources:'리소스', healthLink:'링크', healthPacketLoss:'패킷 손실', probeTargetsCount:'개 프로브 대상', noPeerProbeSamples:'노드 간 프로브 샘플 없음', waitingAgentReport:'에이전트 보고 대기 중', waitingAgent:'에이전트 대기', hostLevelMonitoring:'호스트 수준 모니터링', processUnit:'개' });
Object.assign(LANGUAGE_PACKS.es, { healthResources:'Recursos', healthLink:'Enlace', healthPacketLoss:'Pérdida', probeTargetsCount:'objetivos de sonda', noPeerProbeSamples:'Sin muestras entre nodos', waitingAgentReport:'Esperando informe del agente', waitingAgent:'Esperando agente', hostLevelMonitoring:'Monitoreo a nivel de host', processUnit:'' });
Object.assign(LANGUAGE_PACKS.fr, { healthResources:'Ressources', healthLink:'Liaison', healthPacketLoss:'Perte', probeTargetsCount:'cibles de sonde', noPeerProbeSamples:'Aucun échantillon inter-nœuds', waitingAgentReport:"En attente du rapport de l'agent", waitingAgent:"En attente de l'agent", hostLevelMonitoring:'Surveillance au niveau hôte', processUnit:'' });
Object.assign(LANGUAGE_PACKS.de, { healthResources:'Ressourcen', healthLink:'Verbindung', healthPacketLoss:'Verlust', probeTargetsCount:'Sondenziele', noPeerProbeSamples:'Noch keine Peer-Proben', waitingAgentReport:'Warte auf Agent-Meldung', waitingAgent:'Warte auf Agent', hostLevelMonitoring:'Host-Level-Überwachung', processUnit:'' });
Object.assign(LANGUAGE_PACKS.ru, { healthResources:'Ресурсы', healthLink:'Канал', healthPacketLoss:'Потери', probeTargetsCount:'целей зондирования', noPeerProbeSamples:'Пока нет взаимных проб', waitingAgentReport:'Ожидание отчёта агента', waitingAgent:'Ожидание агента', hostLevelMonitoring:'Мониторинг уровня хоста', processUnit:'' });
// Process-count card: the privacy notice ("total count only, never process names or
// command lines") is a product promise, so it must read correctly in every locale.
Object.assign(LANGUAGE_PACKS.zh, { waitingAgentProcessCount:'等待 Agent 上报进程数', processTotalsOnly:'仅统计总数，不采集进程名称或命令行', noSamplesAvailable:'无可用样本' });
Object.assign(LANGUAGE_PACKS.en, { waitingAgentProcessCount:'Waiting for agent process count', processTotalsOnly:'Total count only — no process names or command lines collected', noSamplesAvailable:'No samples available' });
Object.assign(LANGUAGE_PACKS.ja, { waitingAgentProcessCount:'エージェントのプロセス数待ち', processTotalsOnly:'合計数のみ集計。プロセス名やコマンドラインは収集しません', noSamplesAvailable:'利用可能なサンプルなし' });
Object.assign(LANGUAGE_PACKS.ko, { waitingAgentProcessCount:'에이전트 프로세스 수 대기 중', processTotalsOnly:'총 개수만 집계 — 프로세스 이름이나 명령줄은 수집하지 않음', noSamplesAvailable:'사용 가능한 샘플 없음' });
Object.assign(LANGUAGE_PACKS.es, { waitingAgentProcessCount:'Esperando el recuento de procesos del agente', processTotalsOnly:'Solo el total — no se recopilan nombres de procesos ni líneas de comando', noSamplesAvailable:'Sin muestras disponibles' });
Object.assign(LANGUAGE_PACKS.fr, { waitingAgentProcessCount:"En attente du nombre de processus de l'agent", processTotalsOnly:'Total uniquement — aucun nom de processus ni ligne de commande collecté', noSamplesAvailable:'Aucun échantillon disponible' });
Object.assign(LANGUAGE_PACKS.de, { waitingAgentProcessCount:'Warte auf Prozessanzahl des Agents', processTotalsOnly:'Nur Gesamtzahl — keine Prozessnamen oder Befehlszeilen erfasst', noSamplesAvailable:'Keine Messwerte verfügbar' });
Object.assign(LANGUAGE_PACKS.ru, { waitingAgentProcessCount:'Ожидание числа процессов от агента', processTotalsOnly:'Только общее число — имена процессов и командные строки не собираются', noSamplesAvailable:'Нет доступных выборок' });
// Overview templates are also dynamic HTML, so their visible labels need explicit vocabulary.
Object.assign(LANGUAGE_PACKS.zh, { overviewNodes:'节点', overviewGroups:'分组', overviewAll:'全部', overviewAllNodes:'全部节点', overviewCurrentGroup:'当前分组', overviewNodeAssets:'节点资产', overviewFlatLayout:'全部平铺 · 卡片上显示分组', overviewFilter:'筛选', overviewMasterTop:'主控置顶', overviewNoNodes:'当前筛选下暂无节点', overviewOperatingSummary:'运营摘要', overviewExpiryIn:'天内到期', overviewTraffic:'流量', overviewMaster:'主控', overviewNetworkDetails:'节点网络详情表', overviewUpdatedMissing:'未记录' });
Object.assign(LANGUAGE_PACKS.en, { overviewNodes:'nodes', overviewGroups:'groups', overviewAll:'All', overviewAllNodes:'All nodes', overviewCurrentGroup:'Current group', overviewNodeAssets:'Node assets', overviewFlatLayout:'Flat layout · group shown on cards', overviewFilter:'Filter', overviewMasterTop:'Controller first', overviewNoNodes:'No nodes match this filter', overviewOperatingSummary:'Operations summary', overviewExpiryIn:'days until expiry', overviewTraffic:'Traffic', overviewMaster:'Controller', overviewNetworkDetails:'Node network details', overviewUpdatedMissing:'Not recorded' });
Object.assign(LANGUAGE_PACKS.ja, { overviewNodes:'ノード', overviewGroups:'グループ', overviewAll:'すべて', overviewAllNodes:'全ノード', overviewCurrentGroup:'現在のグループ', overviewNodeAssets:'ノード資産', overviewFlatLayout:'フラット表示 · カードにグループ表示', overviewFilter:'フィルター', overviewMasterTop:'主制御を先頭に', overviewNoNodes:'該当ノードなし', overviewOperatingSummary:'運用サマリー', overviewExpiryIn:'日以内に期限', overviewTraffic:'トラフィック', overviewMaster:'主制御', overviewNetworkDetails:'ノードネットワーク詳細', overviewUpdatedMissing:'記録なし' });
Object.assign(LANGUAGE_PACKS.ko, { overviewNodes:'노드', overviewGroups:'그룹', overviewAll:'전체', overviewAllNodes:'모든 노드', overviewCurrentGroup:'현재 그룹', overviewNodeAssets:'노드 자산', overviewFlatLayout:'평면 보기 · 카드에 그룹 표시', overviewFilter:'필터', overviewMasterTop:'컨트롤러 우선', overviewNoNodes:'필터와 일치하는 노드 없음', overviewOperatingSummary:'운영 요약', overviewExpiryIn:'일 내 만료', overviewTraffic:'트래픽', overviewMaster:'컨트롤러', overviewNetworkDetails:'노드 네트워크 세부 정보', overviewUpdatedMissing:'기록 없음' });
Object.assign(LANGUAGE_PACKS.es, { overviewNodes:'nodos', overviewGroups:'grupos', overviewAll:'Todos', overviewAllNodes:'Todos los nodos', overviewCurrentGroup:'Grupo actual', overviewNodeAssets:'Activos de nodos', overviewFlatLayout:'Vista plana · grupo en tarjetas', overviewFilter:'Filtro', overviewMasterTop:'Controlador primero', overviewNoNodes:'No hay nodos con este filtro', overviewOperatingSummary:'Resumen operativo', overviewExpiryIn:'días hasta vencer', overviewTraffic:'Tráfico', overviewMaster:'Controlador', overviewNetworkDetails:'Detalles de red', overviewUpdatedMissing:'Sin registro' });
Object.assign(LANGUAGE_PACKS.fr, { overviewNodes:'nœuds', overviewGroups:'groupes', overviewAll:'Tous', overviewAllNodes:'Tous les nœuds', overviewCurrentGroup:'Groupe actuel', overviewNodeAssets:'Actifs des nœuds', overviewFlatLayout:'Vue à plat · groupe sur les cartes', overviewFilter:'Filtre', overviewMasterTop:'Contrôleur en tête', overviewNoNodes:'Aucun nœud pour ce filtre', overviewOperatingSummary:'Résumé opérationnel', overviewExpiryIn:'jours avant expiration', overviewTraffic:'Trafic', overviewMaster:'Contrôleur', overviewNetworkDetails:'Détails réseau', overviewUpdatedMissing:'Non enregistré' });
Object.assign(LANGUAGE_PACKS.de, { overviewNodes:'Knoten', overviewGroups:'Gruppen', overviewAll:'Alle', overviewAllNodes:'Alle Knoten', overviewCurrentGroup:'Aktuelle Gruppe', overviewNodeAssets:'Knotenressourcen', overviewFlatLayout:'Flache Ansicht · Gruppe auf Karten', overviewFilter:'Filter', overviewMasterTop:'Controller zuerst', overviewNoNodes:'Keine Knoten für diesen Filter', overviewOperatingSummary:'Betriebsübersicht', overviewExpiryIn:'Tage bis Ablauf', overviewTraffic:'Datenverkehr', overviewMaster:'Controller', overviewNetworkDetails:'Netzwerkdetails', overviewUpdatedMissing:'Nicht erfasst' });
Object.assign(LANGUAGE_PACKS.ru, { overviewNodes:'узлы', overviewGroups:'группы', overviewAll:'Все', overviewAllNodes:'Все узлы', overviewCurrentGroup:'Текущая группа', overviewNodeAssets:'Активы узлов', overviewFlatLayout:'Плоский вид · группа на карточках', overviewFilter:'Фильтр', overviewMasterTop:'Контроллер первым', overviewNoNodes:'Нет узлов по фильтру', overviewOperatingSummary:'Оперативная сводка', overviewExpiryIn:'дней до истечения', overviewTraffic:'Трафик', overviewMaster:'Контроллер', overviewNetworkDetails:'Сведения о сети', overviewUpdatedMissing:'Нет записи' });

export let currentLanguage = safeStorageGet('display_language', 'zh') || 'zh';
// An empty string is a legitimate translation: languages like English have no
// counter word for "N processes", so processUnit is deliberately ''. Falling back
// with `||` treated that as missing and re-inserted the Chinese "个" in every
// non-CJK locale, so presence must be tested instead of truthiness.
export function t(key) {
  const pack = LANGUAGE_PACKS[currentLanguage] || LANGUAGE_PACKS.zh;
  if (Object.prototype.hasOwnProperty.call(pack, key)) return pack[key];
  if (Object.prototype.hasOwnProperty.call(LANGUAGE_PACKS.zh, key)) return LANGUAGE_PACKS.zh[key];
  return key;
}
export function applyLanguage() {
  document.documentElement.setAttribute('lang', currentLanguage);
  document.querySelectorAll('[data-i18n]').forEach((el) => { el.textContent = t(el.dataset.i18n); });
  const lang = document.getElementById('languageSelect');
  if (lang) lang.value = currentLanguage;
  const theme = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
  const label = document.getElementById('themeLabel');
  if (label) label.textContent = theme === 'dark' ? t('bridge') : t('daylight');
  const themeToggle = document.getElementById('themeToggle');
  if (themeToggle) themeToggle.setAttribute('aria-label', t('themeAria'));
}
let languageSwitcherCallbacks = {
  isOverviewMode: () => false,
  getSelectedServerId: () => null,
  renderOverview: () => {},
  // Detail language changes must preserve mounted charts and the star map.
  refreshDetailPresentation: () => {},
};

export function configureLanguageSwitcher(callbacks = {}) {
  languageSwitcherCallbacks = { ...languageSwitcherCallbacks, ...callbacks };
}

export function setLanguage(lang) {
  currentLanguage = LANGUAGE_PACKS[lang] ? lang : 'zh';
  safeStorageSet('display_language', currentLanguage);
  // Admin runs on a separate entry/page; keep its legacy preference in sync and
  // notify same-page consumers without forcing any page remount.
  safeStorageSet('admin_lang', currentLanguage);
  window.dispatchEvent(new CustomEvent('vps-language-changed', { detail: { language: currentLanguage } }));
  applyLanguage();
  if (languageSwitcherCallbacks.isOverviewMode()) languageSwitcherCallbacks.renderOverview();
  else {
    const serverId = languageSwitcherCallbacks.getSelectedServerId();
    if (serverId) languageSwitcherCallbacks.refreshDetailPresentation({ languageChanged: true });
  }
}


export function setTheme(theme) {
  document.documentElement.setAttribute('data-theme', theme);
  safeStorageSet('display_theme', theme);
  const icon = document.getElementById('themeIcon');
  const label = document.getElementById('themeLabel');
  if (icon) icon.textContent = theme === 'dark' ? '☾' : '☀';
  if (label) label.textContent = theme === 'dark' ? t('bridge') : t('daylight');
}

export function toggleTheme() {
  const current = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
  setTheme(current === 'dark' ? 'light' : 'dark');
}
