import { getCurrentUser, changePassword, updateProfile, getTwoFactorStatus, setupTwoFactor, enableTwoFactor, disableTwoFactor, getExternalAccounts, unlinkExternalAccount, externalAccountBindUrl } from '../../api/admin.js';

export class AccountPanel {
  constructor(mountId) { this._el=document.getElementById(mountId); this._user=null; this._render(); this._bind(); }
  _render(){ this._el.innerHTML=`
    <div class="komari-settings-page komari-account-page">
      <div class="komari-page-head"><div><h2>账户</h2><p>管理用户名、密码和双因素认证。</p></div></div>
      <section class="komari-flat-section"><h3>更改用户名</h3><div class="komari-form-grid one"><label class="komari-field-plain"><input id="acct-username" class="form-input" value="admin" autocomplete="username"></label></div><div class="komari-action-row"><button id="acct-username-btn" class="komari-primary">修改用户名</button></div><div id="acct-user-msg" class="komari-msg"></div></section>
      <section class="komari-flat-section"><h3>修改密码</h3><div class="komari-form-grid one komari-narrow-form"><label class="komari-current-pass"><span>当前密码</span><input id="acct-old" type="password" class="form-input" autocomplete="current-password"></label><label><span>新密码</span><input id="acct-new" type="password" class="form-input" autocomplete="new-password"></label><label><span>重复新密码</span><input id="acct-new2" type="password" class="form-input" autocomplete="new-password"></label></div><div class="komari-action-row"><button id="acct-random-password" class="komari-secondary" type="button">生成随机密码</button><button id="acct-copy-password" class="komari-secondary" type="button">复制新密码</button><button id="acct-toggle-password" class="komari-secondary" type="button" aria-pressed="false">显示密码</button><button id="acct-change-btn" class="komari-primary">更改密码</button></div><p class="komari-muted-line">随机密码仅在浏览器本地生成，不会保存；提交前请先复制保存。</p><div id="acct-msg" class="komari-msg"></div></section>
      <section class="komari-flat-section"><h3>双因素认证</h3><p class="komari-muted-line" id="acct-2fa-state">加载中...</p><div id="acct-2fa-setup" class="komari-muted-line"></div><div class="komari-form-grid one komari-narrow-form"><label><span>验证码</span><input id="acct-2fa-code" class="form-input" inputmode="numeric" autocomplete="one-time-code" placeholder="6 位验证码"></label><label><span>当前密码（关闭时需要）</span><input id="acct-2fa-pass" class="form-input" type="password" autocomplete="current-password"></label></div><div class="komari-action-row"><button class="komari-primary" id="acct-2fa-btn">开启双重身份验证</button><button class="komari-secondary" id="acct-2fa-disable">关闭</button></div><div id="acct-2fa-msg" class="komari-msg"></div></section>
      <section class="komari-flat-section"><h3>单点登录</h3><div class="komari-external-title">👤 外部账户</div><div class="komari-bind-card" id="acct-bind-card"><span>加载中</span><span>加载中</span></div><div class="komari-action-row"><button class="komari-primary" id="acct-bind-google">绑定 Google</button><button class="komari-primary" id="acct-bind-github">绑定 GitHub</button></div><div id="acct-bind-msg" class="komari-msg"></div></section>
      <section class="komari-panel komari-account-advanced"><div class="komari-panel-title"><span>账户资料</span><small>当前管理员账号</small></div><div id="acct-summary" class="komari-kv-box">加载中...</div><p class="komari-muted-line acct-session-handoff">登录设备、来源 IP、最近活跃和退出其他设备统一在「登录会话」中管理。</p></section>
    </div>`; }
  _bind(){ this._el.querySelector('#acct-change-btn').addEventListener('click',()=>this._submitPassword()); this._el.querySelector('#acct-random-password').addEventListener('click',()=>this._fillRandomPassword()); this._el.querySelector('#acct-copy-password').addEventListener('click',()=>this._copyNewPassword()); this._el.querySelector('#acct-toggle-password').addEventListener('click',()=>this._togglePasswordVisibility()); this._el.querySelector('#acct-username-btn').addEventListener('click',()=>this._submitUsername()); this._el.querySelector('#acct-2fa-btn').addEventListener('click',()=>this._enable2fa()); this._el.querySelector('#acct-2fa-disable').addEventListener('click',()=>this._disable2fa()); this._el.querySelector('#acct-bind-google').addEventListener('click',()=>{ location.href=externalAccountBindUrl('google'); }); this._el.querySelector('#acct-bind-github').addEventListener('click',()=>{ location.href=externalAccountBindUrl('github'); }); }
  async load(){ this._load2fa(); this._loadExternal();
 const box=this._el.querySelector('#acct-summary'); box.textContent='加载中...'; try{ const data=await getCurrentUser(); this._user=data.user||null; const u=this._user||{}; this._el.querySelector('#acct-username').value=u.username||'admin'; box.innerHTML=`<div><span>用户名</span><b>${esc(u.username||'-')}</b></div><div><span>邮箱</span><b>${esc(u.email||'-')}</b></div><div><span>邮箱验证</span><b><span class="acct-pill ${u.email_verified?'ok':'warn'}">${u.email_verified?'已验证':'未验证'}</span></b></div><div><span>角色</span><b><span class="acct-pill role">${esc(u.role||'-')}</span></b></div><div><span>创建时间</span><b>${esc(fmt(u.created_at)||'—')}</b></div><div><span>最后登录</span><b>${esc(fmt(u.last_login)||'—')}</b></div>`;}catch(err){box.innerHTML=`<em>账户信息加载失败：${esc(err.message||'unknown')}</em>`;} }
  async _submitUsername(){ const username=this._el.querySelector('#acct-username').value.trim(); if(!username)return this._flashUser('用户名不能为空','err'); try{ const data=await updateProfile({ username }); this._user=data.user||this._user; this._flashUser('用户名已更新','ok'); await this.load(); }catch(err){ this._flashUser(err.message||'用户名更新失败','err'); } }
  async _load2fa(){ try{ const st=await getTwoFactorStatus(); this._2faEnabled=!!st.enabled; this._el.querySelector('#acct-2fa-state').textContent=this._2faEnabled?'双重身份验证已开启':'双重身份验证已禁用'; this._el.querySelector('#acct-2fa-btn').disabled=this._2faEnabled; this._el.querySelector('#acct-2fa-disable').disabled=!this._2faEnabled; if(!this._2faEnabled){ const setup=await setupTwoFactor(); this._pending2faSecret=setup.secret; this._el.querySelector('#acct-2fa-setup').innerHTML=`密钥：<code>${esc(setup.secret||'')}</code><br><small>${esc(setup.otpauth_url||'')}</small>`; }else{ this._el.querySelector('#acct-2fa-setup').textContent='登录时将要求输入 6 位验证码。'; } }catch(err){ const unavailable=err.status===501; this._el.querySelector('#acct-2fa-state').textContent=unavailable?'双因素认证暂未开放':('2FA 状态加载失败：'+(err.message||'unknown')); this._el.querySelector('#acct-2fa-btn').disabled=true; this._el.querySelector('#acct-2fa-disable').disabled=true; if(unavailable)this._el.querySelector('#acct-2fa-setup').textContent='该功能尚未实现，已禁用。'; } }
  async _enable2fa(){ const code=this._el.querySelector('#acct-2fa-code').value.trim(); try{ await enableTwoFactor(code,this._pending2faSecret||''); this._flash2fa('双因素认证已开启','ok'); await this._load2fa(); }catch(err){ this._flash2fa(err.message||'开启失败','err'); } }
  async _disable2fa(){ const password=this._el.querySelector('#acct-2fa-pass').value; const code=this._el.querySelector('#acct-2fa-code').value.trim(); try{ await disableTwoFactor(password,code); this._flash2fa('双因素认证已关闭','ok'); this._el.querySelector('#acct-2fa-pass').value=''; await this._load2fa(); }catch(err){ this._flash2fa(err.message||'关闭失败','err'); } }
  async _loadExternal(){ const card=this._el.querySelector('#acct-bind-card'); try{ const data=await getExternalAccounts(); const acc=data.accounts||{}; const prov=data.oauth_providers||{}; card.innerHTML=['google','github'].map(p=>{const a=acc[p]; return `<span>${p.toUpperCase()}</span><span>${a?('已绑定 '+esc(a.provider_email||a.provider_name||'')):(prov[p]?'未绑定':'OAuth 未配置')}</span>`}).join(''); this._el.querySelector('#acct-bind-google').disabled=!prov.google; this._el.querySelector('#acct-bind-github').disabled=!prov.github; }catch(err){ const unavailable=err.status===501; card.innerHTML=unavailable?'<span>单点登录暂未开放</span><span>该功能尚未实现，已禁用。</span>':`<span>加载失败</span><span>${esc(err.message||'unknown')}</span>`; if(unavailable){ this._el.querySelector('#acct-bind-google').disabled=true; this._el.querySelector('#acct-bind-github').disabled=true; } } }

  _flash2fa(text,kind){ const el=this._el.querySelector('#acct-2fa-msg'); el.textContent=text; el.className=`komari-msg ${kind}`; }
  _secureRandomIndex(upperBound){ const cryptoObj=window.crypto||window.msCrypto; if(!cryptoObj?.getRandomValues)throw new Error('当前浏览器不支持安全随机数生成，请手动设置密码'); const limit=Math.floor(0x100000000/upperBound)*upperBound; const a=new Uint32Array(1); do{ cryptoObj.getRandomValues(a); }while(a[0]>=limit); return a[0]%upperBound; }
  _generateStrongPassword(length=24){ const groups=['abcdefghijkmnopqrstuvwxyz','ABCDEFGHJKLMNPQRSTUVWXYZ','23456789','!@#$%^*-_+']; const all=groups.join(''); const pick=(chars)=>chars[this._secureRandomIndex(chars.length)]; const chars=groups.map(pick); while(chars.length<length)chars.push(pick(all)); for(let i=chars.length-1;i>0;i--){ const j=this._secureRandomIndex(i+1); [chars[i],chars[j]]=[chars[j],chars[i]]; } return chars.join(''); }
  _passwordInputs(){ return ['#acct-new','#acct-new2'].map(s=>this._el.querySelector(s)); }
  _setPasswordVisibility(reveal){ this._passwordInputs().forEach(input=>{ input.type=reveal?'text':'password'; }); const button=this._el.querySelector('#acct-toggle-password'); button.textContent=reveal?'隐藏密码':'显示密码'; button.setAttribute('aria-pressed',String(reveal)); }
  _togglePasswordVisibility(){ const reveal=this._el.querySelector('#acct-new').type==='password'; this._setPasswordVisibility(reveal); }
  _fillRandomPassword(){ try{ const pw=this._generateStrongPassword(); this._passwordInputs().forEach(input=>{ input.value=pw; }); this._setPasswordVisibility(false); this._flash('已生成随机强密码，请先复制保存后再提交。','ok'); }catch(err){ this._flash(err.message||'生成密码失败','err'); } }
  async _copyNewPassword(){ const pw=this._el.querySelector('#acct-new').value; if(!pw)return this._flash('请先生成或填写新密码','err'); try{ await navigator.clipboard.writeText(pw); this._flash('新密码已复制到剪贴板，请妥善保存。','ok'); }catch{ this._flash('复制失败，请点击“显示密码”后手动复制。','err'); }finally{ this._setPasswordVisibility(false); } }
  async _submitPassword(){ const oldPassword=this._el.querySelector('#acct-old').value; const newPassword=this._el.querySelector('#acct-new').value; const newPassword2=this._el.querySelector('#acct-new2').value; if(!oldPassword||!newPassword||!newPassword2)return this._flash('请填写完整密码字段','err'); if(newPassword!==newPassword2)return this._flash('两次输入的新密码不一致','err'); try{ await changePassword(oldPassword,newPassword); ['#acct-old','#acct-new','#acct-new2'].forEach(s=>this._el.querySelector(s).value=''); this._flash('密码已更新','ok'); }catch(err){ this._flash(err.message||'密码更新失败','err'); }finally{ this._setPasswordVisibility(false); } }
  _flash(text,kind){ const el=this._el.querySelector('#acct-msg'); el.textContent=text; el.className=`komari-msg ${kind}`; }
  _flashUser(text,kind){ const el=this._el.querySelector('#acct-user-msg'); el.textContent=text; el.className=`komari-msg ${kind}`; }
}
function fmt(v){ if(!v)return''; try{return new Date(v).toLocaleString('zh-CN');}catch{return String(v);} }
function esc(s){return String(s||'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
