/** Komari-inspired 默认主题设置：本地保存 + 预览，不假装有后端全局主题 */
const THEMES=[
{name:'星图深空',key:'starmap',desc:'当前项目默认，适合地球星图首页',swatches:['#050814','#66d9ff','#58f2b1','#ff6b81'],vars:{'--bg-base':'#050814','--bg-panel':'rgba(10,16,32,.78)','--primary':'#66d9ff','--primary-hover':'#8be5ff','--text-main':'#edf5ff','--text-muted':'#8ea7c7','--border':'rgba(120,182,255,.16)','--red':'#ff6b81','--green':'#58f2b1'}},
{name:'Komari 浅色',key:'komari-light',desc:'接近 Komari 设置页，但保留 VPS 星图强调色',swatches:['#f7f8fb','#ffffff','#6366f1','#ef4444'],vars:{'--bg-base':'#f7f8fb','--bg-panel':'#ffffff','--primary':'#6366f1','--primary-hover':'#4f46e5','--text-main':'#111827','--text-muted':'#64748b','--border':'#e5e7eb','--red':'#ef4444','--green':'#16a34a'}},
{name:'运维暗色',key:'ops-dark',desc:'高对比，适合长时间监控',swatches:['#0f172a','#1e293b','#38bdf8','#22c55e'],vars:{'--bg-base':'#0f172a','--bg-panel':'#111827','--primary':'#38bdf8','--primary-hover':'#7dd3fc','--text-main':'#f8fafc','--text-muted':'#94a3b8','--border':'#334155','--red':'#fb7185','--green':'#22c55e'}},
{name:'冰川极区',key:'ice',desc:'和极区冰雪兜底色协调',swatches:['#edf4fb','#ffffff','#3b82f6','#0f766e'],vars:{'--bg-base':'#edf4fb','--bg-panel':'#ffffff','--primary':'#3b82f6','--primary-hover':'#2563eb','--text-main':'#102033','--text-muted':'#64748b','--border':'#dbe7f3','--red':'#ef4444','--green':'#0f766e'}}
];
export class ThemeEditor{constructor(mountId){this._el=document.getElementById(mountId);this._activeKey=localStorage.getItem('vps_default_theme')||'starmap';this._render();this._bind();this._applyTheme(this._activeKey,false);this._loadSavedCSS();}
_render(){this._el.innerHTML=`<div class="komari-settings-page"><div class="komari-page-head"><div><h2>默认主题设置</h2><p>复刻 Komari 的主题选择体验，但当前只作用于本管理端浏览器；不影响前台地球材质和节点数据。</p></div><button class="komari-secondary" id="te-reset-all">恢复默认</button></div><section class="komari-panel"><div class="komari-panel-title"><span>主题预设</span><small>local default</small></div><div class="komari-theme-grid" id="te-presets"></div></section><section class="komari-panel"><div class="komari-panel-title"><span>当前主题预览</span><small id="te-current-name"></small></div><div class="komari-theme-preview"><div><strong>VPS 星图后台</strong><span>ONLINE</span></div><div><em>CPU 32%</em><em>延迟 64ms</em><em>告警 2</em></div></div></section><section class="komari-panel"><div class="komari-panel-title"><span>自定义 CSS</span><small>高级覆盖，本地保存</small></div><textarea class="css-editor" id="te-css" placeholder=":root { --primary: #66d9ff; }"></textarea><div class="komari-action-row"><button class="komari-primary" id="te-preview">实时预览</button><button class="komari-secondary" id="te-save-css">保存 CSS</button><button class="komari-secondary" id="te-reset-css">清空 CSS</button></div><div id="te-css-msg" class="komari-msg"></div></section></div>`;this._renderPresets();}
_renderPresets(){this._el.querySelector('#te-presets').innerHTML=THEMES.map(t=>`<button class="komari-theme-card ${t.key===this._activeKey?'active':''}" data-theme-key="${t.key}"><span>${t.swatches.map(c=>`<i style="background:${c}"></i>`).join('')}</span><b>${t.name}</b><small>${t.desc}</small></button>`).join('');}
_applyTheme(key,save=true){const t=THEMES.find(x=>x.key===key)||THEMES[0];this._activeKey=t.key;if(save)localStorage.setItem('vps_default_theme',t.key);Object.entries(t.vars).forEach(([k,v])=>document.documentElement.style.setProperty(k,v));this._el.querySelector('#te-current-name').textContent=t.name;this._renderPresets();}
_bind(){this._el.querySelector('#te-presets').addEventListener('click',e=>{const card=e.target.closest('[data-theme-key]');if(card)this._applyTheme(card.dataset.themeKey,true);});this._el.querySelector('#te-reset-all').addEventListener('click',()=>{localStorage.removeItem('vps_default_theme');localStorage.removeItem('vps_custom_css');document.getElementById('custom-css-inject')?.remove();this._applyTheme('starmap',true);this._el.querySelector('#te-css').value='';this._msg('已恢复默认主题','ok');});this._el.querySelector('#te-preview').addEventListener('click',()=>{this._injectCSS(this._el.querySelector('#te-css').value);this._msg('CSS 已预览','ok');});this._el.querySelector('#te-save-css').addEventListener('click',()=>{const css=this._el.querySelector('#te-css').value;localStorage.setItem('vps_custom_css',css);this._injectCSS(css);this._msg('CSS 已保存','ok');});this._el.querySelector('#te-reset-css').addEventListener('click',()=>{this._el.querySelector('#te-css').value='';localStorage.removeItem('vps_custom_css');document.getElementById('custom-css-inject')?.remove();this._msg('CSS 已清空','ok');});}
_loadSavedCSS(){const saved=localStorage.getItem('vps_custom_css')||'';this._el.querySelector('#te-css').value=saved;if(saved)this._injectCSS(saved);}
_injectCSS(css){let tag=document.getElementById('custom-css-inject');if(!tag){tag=document.createElement('style');tag.id='custom-css-inject';document.head.appendChild(tag);}tag.textContent=css;}
_msg(text,kind){const el=this._el.querySelector('#te-css-msg');el.textContent=text;el.className=`komari-msg ${kind}`;}
}
